name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish CPM.cmake
    runs-on: ubuntu-latest
    steps:
      - name: Upload CPM.cmake to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmake/CPM.cmake
          asset_name: CPM.cmake
          tag: ${{ github.ref }}
          overwrite: true
