name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish CPM.cmake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set CPM version by tag
        run: |
          mkdir dist
          sed "s/1.0.0-development-version/${GITHUB_REF/refs\/tags\/v}/g" cmake/CPM.cmake > dist/CPM.cmake
          sed "s/1.0.0-development-version/${GITHUB_REF/refs\/tags\/v}/g" cmake/get_cpm.cmake > dist/get_cpm.cmake

      - name: Upload CPM.cmake to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: dist/*.cmake
          file_glob: true
          overwrite: true
